config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users

  resources :ideas

  root 'home#index'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

end

app/models/idea.rb
class Idea < ActiveRecord::Base
  acts_as_authorization_object 
  validates :name, presence: true
  validates_numericality_of :passion_rating, :only_integer => true, :less_than => 6, :greater_than => 0
  validates_numericality_of :skill_rating, :only_integer => true, :less_than => 6, :greater_than => 0
  validates_numericality_of :profit_rating, :only_integer => true, :less_than => 6, :greater_than => 0

  scope :roled_by, -> ( r, u ) { where id: u.role_objects.select(:authorizable_id).where( :name => r, :authorizable_type => self ) }
  scope :owned_by, -> (u) { roled_by :owner, u }
end

# == Schema Information
#
# Table name: ideas
#
#  id             :integer          not null, primary key
#  name           :string(255)
#  description    :string(255)
#  profit_rating  :integer
#  skill_rating   :integer
#  passion_rating :integer
#  created_at     :datetime
#  updated_at     :datetime
#

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  access_control :debug => true do
    allow :owner, :of => :idea, :to => [:show, :edit, :update, :destroy]
    allow logged_in, :to => [:index, :new, :create]
  end

# GET /ideas
# GET /ideas.json
  def index
    @ideas = current_user.ideas
  end

# GET /ideas/1
# GET /ideas/1.json
  def show
  end

# GET /ideas/new
  def new
    @idea = Idea.new passion_rating: 1, skill_rating: 1, profit_rating: 1
  end

# GET /ideas/1/edit
  def edit
  end

# POST /ideas
# POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        current_user.has_role! :owner, @idea
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

# PATCH/PUT /ideas/1
# PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

# DELETE /ideas/1
# DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
# Use callbacks to share common setup or constraints between actions.
  def set_idea
    @idea = Idea.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def idea_params
    params.require(:idea).permit(:name, :description, :profit_rating, :skill_rating, :passion_rating)
  end

end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => { :class => "form-horizontal idea" } do |f| %>

    <% if @idea.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @idea.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%= error_span(@idea[:name]) %>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'form-control' %>
    </div>
    <%= error_span(@idea[:description]) %>
  </div>
  <div class="control-group">
    <%= f.label :profit_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :profit_rating, :class => 'form-control' %>
    </div>
    <%= error_span(@idea[:profit_rating]) %>
  </div>
  <div class="control-group">
    <%= f.label :skill_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :skill_rating, :class => 'form-control' %>
    </div>
    <%= error_span(@idea[:skill_rating]) %>
  </div>
  <div class="control-group">
    <%= f.label :passion_rating, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :passion_rating, :class => 'form-control' %>
    </div>
    <%= error_span(@idea[:passion_rating]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            ideas_path, :class => 'btn btn-default' %>

<% end %>

app/views/ideas/edit.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ideas/index.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%= t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
    <th><%= model_class.human_attribute_name(:profit_rating) %></th>
    <th><%= model_class.human_attribute_name(:skill_rating) %></th>
    <th><%= model_class.human_attribute_name(:passion_rating) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%= t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @ideas.each do |idea| %>
      <tr>
        <td><%= link_to idea.id, idea_path(idea) %></td>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.profit_rating %></td>
        <td><%= idea.skill_rating %></td>
        <td><%= idea.passion_rating %></td>
        <td><%= local_time(idea.created_at) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_idea_path(idea), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      idea_path(idea),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_idea_path,
            :class => 'btn btn-primary' %>

app/views/ideas/new.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ideas/show.html.erb
<%- model_class = Idea -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @idea.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @idea.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:profit_rating) %>:</strong></dt>
  <dd><%= @idea.profit_rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:skill_rating) %>:</strong></dt>
  <dd><%= @idea.skill_rating %></dd>
  <dt><strong><%= model_class.human_attribute_name(:passion_rating) %>:</strong></dt>
  <dd><%= @idea.passion_rating %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              ideas_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_idea_path(@idea), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              idea_path(@idea),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>