config/routes.rb
Rails.application.routes.draw do

  resources :user_sessions
  resources :users

  resources :ideas

  root 'home#index'

  get 'login' => 'user_sessions#new', :as => :login
  post 'logout' => 'user_sessions#destroy', :as => :logout

  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github
  get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider
  delete "oauth/:provider" => "oauths#destroy", :as => :delete_oauth

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]
  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      redirect_back_or_to(root_path, notice: 'Login successful')
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email %><br />
      <%= text_field_tag :email %>
    </div>
    <div class="field">
      <%= label_tag :password %><br />
      <%= password_field_tag :password %>
    </div>
    <div class="actions">
      <%= submit_tag 'Login', :class => 'btn btn-lg btn-success' %>
    </div>
<% end %>
<div style="text-align: right;">
  <% if logged_in? %>
      Currently logged in as: <%= current_user.email %> |

      <% if current_user.has_linked_github? %>
          <%= link_to 'Unlink your Github account', delete_oauth_path('github'), method: :delete %>
      <% else %>
          <%= link_to 'Link your GitHub account', auth_at_provider_path(:provider => :github) %>
      <% end %> |

      <%= link_to 'Logout', logout_path %>
  <% else %>
      <%= link_to 'Login', login_path %> |
      <%= link_to 'Login using Github', auth_at_provider_path(provider: :github) %>
  <% end %>
</div>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>